import "../globals.css";

export const metadata = {
  title: 'Nhất Tín',
  description: 'Generated by Next.js',
}

export default function OrderLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return children;
}
