export const metadata = {
  title: 'Nhất Tín - Chi tiết sản phẩm',
  description: 'Generated by Next.js',
}

export default function ProductDetailLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return children;
}
